//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EQueueClient.AgentService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgentService.AgentServiceSoap")]
    public interface AgentServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 url 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Invoke", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EQueueClient.AgentService.ArrayOfAnyType))]
        EQueueClient.AgentService.InvokeResponse Invoke(EQueueClient.AgentService.InvokeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Invoke", Namespace="http://tempuri.org/", Order=0)]
        public EQueueClient.AgentService.InvokeRequestBody Body;
        
        public InvokeRequest() {
        }
        
        public InvokeRequest(EQueueClient.AgentService.InvokeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvokeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string methodName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string className;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public EQueueClient.AgentService.ArrayOfAnyType args;
        
        public InvokeRequestBody() {
        }
        
        public InvokeRequestBody(string url, string methodName, string className, EQueueClient.AgentService.ArrayOfAnyType args) {
            this.url = url;
            this.methodName = methodName;
            this.className = className;
            this.args = args;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeResponse", Namespace="http://tempuri.org/", Order=0)]
        public EQueueClient.AgentService.InvokeResponseBody Body;
        
        public InvokeResponse() {
        }
        
        public InvokeResponse(EQueueClient.AgentService.InvokeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvokeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object InvokeResult;
        
        public InvokeResponseBody() {
        }
        
        public InvokeResponseBody(object InvokeResult) {
            this.InvokeResult = InvokeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentServiceSoapChannel : EQueueClient.AgentService.AgentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentServiceSoapClient : System.ServiceModel.ClientBase<EQueueClient.AgentService.AgentServiceSoap>, EQueueClient.AgentService.AgentServiceSoap {
        
        public AgentServiceSoapClient() {
        }
        
        public AgentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EQueueClient.AgentService.InvokeResponse EQueueClient.AgentService.AgentServiceSoap.Invoke(EQueueClient.AgentService.InvokeRequest request) {
            return base.Channel.Invoke(request);
        }
        
        public object Invoke(string url, string methodName, string className, EQueueClient.AgentService.ArrayOfAnyType args) {
            EQueueClient.AgentService.InvokeRequest inValue = new EQueueClient.AgentService.InvokeRequest();
            inValue.Body = new EQueueClient.AgentService.InvokeRequestBody();
            inValue.Body.url = url;
            inValue.Body.methodName = methodName;
            inValue.Body.className = className;
            inValue.Body.args = args;
            EQueueClient.AgentService.InvokeResponse retVal = ((EQueueClient.AgentService.AgentServiceSoap)(this)).Invoke(inValue);
            return retVal.Body.InvokeResult;
        }
    }
}
